In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [21]:
df_tmp = pd.read_html('https://tw.stock.yahoo.com/s/list.php?c=%A8T%A8%AE&rr=0.51853600%201573389823',encoding='big5')

In [22]:
len(df_tmp)

5

In [23]:
for i,table in enumerate(df_tmp):
    print(i,len(table))

0 1
1 1
2 31
3 1
4 1

In [24]:
df_tmp[2].head()

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1319 東陽,14:30,46.90,46.85,46.90,▽0.15,825,47.05,47.05,47.40,46.50
1,NaN,1338 廣華-KY,13:30,62.80,62.60,62.90,△0.3,85,62.50,62.50,62.90,62.40
2,NaN,1339 昭輝,14:30,46.15,46.10,46.20,△1.20,462,44.95,45.50,46.40,45.40
3,NaN,1512 瑞利,13:24,5.29,5.20,5.29,△0.09,57,5.20,5.19,5.29,5.19
4,NaN,1521 大億,13:30,64.70,64.70,65.00,▽0.2,46,64.90,64.90,65.00,64.70

In [25]:
df=df_tmp[2]

In [26]:
df.head()

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1319 東陽,14:30,46.90,46.85,46.90,▽0.15,825,47.05,47.05,47.40,46.50
1,NaN,1338 廣華-KY,13:30,62.80,62.60,62.90,△0.3,85,62.50,62.50,62.90,62.40
2,NaN,1339 昭輝,14:30,46.15,46.10,46.20,△1.20,462,44.95,45.50,46.40,45.40
3,NaN,1512 瑞利,13:24,5.29,5.20,5.29,△0.09,57,5.20,5.19,5.29,5.19
4,NaN,1521 大億,13:30,64.70,64.70,65.00,▽0.2,46,64.90,64.90,65.00,64.70

In [28]:
df.drop('選擇',axis=1,inplace=True)

In [29]:
df.head()

,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,1319 東陽,14:30,46.90,46.85,46.90,▽0.15,825,47.05,47.05,47.40,46.50
1,1338 廣華-KY,13:30,62.80,62.60,62.90,△0.3,85,62.50,62.50,62.90,62.40
2,1339 昭輝,14:30,46.15,46.10,46.20,△1.20,462,44.95,45.50,46.40,45.40
3,1512 瑞利,13:24,5.29,5.20,5.29,△0.09,57,5.20,5.19,5.29,5.19
4,1521 大億,13:30,64.70,64.70,65.00,▽0.2,46,64.90,64.90,65.00,64.70

In [36]:
df_sorted = df.sort_values(by="漲跌")

In [45]:
df_sorted

,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
30,6605 帝寶,13:30,61.50,61.50,61.70,0.00,92,61.50,61.50,61.70,61.50
11,1587 吉茂,13:30,16.60,16.50,16.60,0.00,25,16.60,16.55,16.60,16.55
24,2243 宏旭-KY,13:04,13.40,13.35,13.40,△0.05,8,13.35,13.70,13.70,13.35
8,1533 車王電,13:30,36.80,36.80,36.95,△0.05,54,36.75,36.80,37.20,36.75
3,1512 瑞利,13:24,5.29,5.20,5.29,△0.09,57,5.20,5.19,5.29,5.19
16,2206 三陽工業,13:30,22.15,22.10,22.15,△0.10,764,22.05,22.05,22.15,22.05
13,2115 六暉-KY,11:59,39.05,39.00,39.05,△0.10,26,38.95,39.40,39.40,39.05
15,2204 中華,13:30,41.00,40.95,41.05,△0.15,250,40.85,41.05,41.05,40.75
28,4557 永新-KY,13:15,68.70,68.60,68.80,△0.2,16,68.50,68.50,68.70,68.50
1,1338 廣華-KY,13:30,62.80,62.60,62.90,△0.3,85,62.50,62.50,62.90,62.40
5,1522 堤維西,14:30,29.80,29.80,29.85,△0.45,1504,29.35,29.30,29.90,29.30
9,1536 和大,13:30,113.00,113.00,113.50,△0.5,401,112.50,113.50,114.00,112.50
29,6288 聯嘉,14:30,25.05,25.05,25.10,△0.95,4993,24.10,24.30,25.60,24.25
2,1339 昭輝,14:30,46.15,46.10,46.20,△1.20,462,44.95,45.50,46.40,45.40
19,2228 劍麟,14:30,122.50,122.50,123.00,△1.5,416,121.00,122.50,124.00,121.50
27,4551 智伸科,13:30,172.50,172.50,173.50,△1.5,428,171.00,171.50,175.00,171.50
18,2227 裕日車,13:30,265.00,264.50,265.00,△3.5,80,261.50,265.00,265.50,263.00
17,2207 和泰車,14:30,575.00,574.00,575.00,△9,326,566.00,567.00,575.00,563.00
6,1524 耿鼎,13:30,9.97,9.97,10.00,▽0.01,35,9.98,10.00,10.00,9.97
26,3346 麗清,14:30,31.10,31.05,31.10,▽0.05,225,31.15,31.00,31.10,30.85
14,2201 裕隆,14:30,19.15,19.15,19.20,▽0.05,2640,19.20,19.20,19.30,19.05
21,2233 宇隆,13:30,70.20,70.20,70.40,▽0.1,118,70.30,70.30,70.40,70.10
0,1319 東陽,14:30,46.90,46.85,46.90,▽0.15,825,47.05,47.05,47.40,46.50
7,1525 江申,13:21,56.00,55.90,56.00,▽0.2,18,56.20,56.00,56.50,55.60
4,1521 大億,13:30,64.70,64.70,65.00,▽0.2,46,64.90,64.90,65.00,64.70
22,2236 百達-KY,13:30,21.40,21.10,21.45,▽0.20,15,21.60,21.40,21.40,21.20
12,1592 英瑞-KY,13:30,19.80,19.70,19.80,▽0.35,981,20.15,20.15,20.15,19.60
10,1568 倉佑,13:30,19.25,19.20,19.25,▽0.35,236,19.60,19.70,19.70,19.10
25,2497 怡利電,14:30,23.25,23.25,23.40,▽0.55,462,23.80,23.85,23.85,23.05
23,2239 英利-KY,13:30,91.10,91.10,91.30,▽1.3,106,92.40,92.10,92.10,91.00
20,2231 為升,13:30,234.50,234.50,235.50,▽7.0,852,241.50,241.50,243.00,231.50

In [38]:
df_sorted["張數"].mean()

533.741935483871

In [44]:
df_sorted["張數"].std()

992.6548231129804